services:
  db:
    image: postgres:15-alpine
    container_name: mep-db
    environment:
      POSTGRES_DB: market_edge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: [mep_db_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d market_edge || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports: ["5432:5432"]   # optional; remove if you don't need host access

  migrate:
    image: ghcr.io/manalbuquerque/market_edge_pro_backend_v2:v0.2.5
    container_name: mep-migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/market_edge
    command: ["sh","-lc","alembic upgrade head || true"]
    volumes:
      - ./alembic:/app/alembic:ro
      - ./alembic.ini:/app/alembic.ini:ro

  seed:
    image: postgres:15-alpine
    container_name: mep-seed
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./seeds:/seeds:ro
    command: ["sh","-lc","psql postgresql://postgres:postgres@db:5432/market_edge -f /seeds/ohlcv_seed.sql || true"]

  app:
    image: ghcr.io/manalbuquerque/market_edge_pro_backend_v2:v0.2.5
    container_name: mep-app
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      seed:
        condition: service_completed_successfully
    environment:
      APIKEY_ENABLED: "1"
      API_KEYS: secret123
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/market_edge
    command: >
      uvicorn main1:app --host 0.0.0.0 --port 8010
    ports: ["8010:8010"]
    restart: unless-stopped

volumes:
  mep_db_data:
