services:
  db:
    image: postgres:15-alpine
    container_name: mep-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-market_edge}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - mep_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-market_edge} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"

  app:
    build: .
    image: mep-app:dev
    container_name: mep-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      APIKEY_ENABLED: ${APIKEY_ENABLED:-1}
      API_KEYS: ${API_KEYS:-secret123}
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@db:5432/market_edge}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-whsec_dev}
    command: >
      uvicorn main1:app --host 0.0.0.0 --port 8010
    ports:
      - "8010:8010"
    restart: unless-stopped

  migrate:
    build: .
    image: mep-app:dev
    container_name: mep-migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@db:5432/market_edge}
    command: ["sh","-lc","alembic upgrade head || true"]

  seed:
    image: postgres:15-alpine
    container_name: mep-seed
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./seeds:/seeds:ro
    command: ["sh","-lc","psql postgresql://postgres:postgres@db:5432/market_edge -f /seeds/ohlcv_seed.sql || true"]

volumes:
  mep_db_data:
