services:
  db:
    image: postgres:15-alpine
    container_name: mep-db
    environment:
      POSTGRES_DB: market_edge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - mep_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d market_edge || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"

  app:
    image: ghcr.io/manalbuquerque/market_edge_pro_backend_v2:v0.2.5
    container_name: mep-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # API key system
      APIKEY_ENABLED: "1"
      API_KEYS: "secret123"
      # make webhook public (no API key required)
      APIKEY_PUBLIC: "/docs,/openapi.json,/health,/healthz,/ready,/readyz,/metrics,/stripe/webhook"
      # DB (service hostname is 'db')
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@db:5432/market_edge"
      # optional: if you set a real Stripe signing secret later
      # STRIPE_WEBHOOK_SECRET: "whsec_xxx"
    command: >
      uvicorn main1:app
      --host 0.0.0.0
      --port 8010
    ports:
      - "8010:8010"
    restart: unless-stopped

  migrate:
    image: ghcr.io/manalbuquerque/market_edge_pro_backend_v2:v0.2.5
    container_name: mep-migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@db:5432/market_edge"
    # use YOUR local migrations + ini (so env.py honors DATABASE_URL)
    volumes:
      - ./migrations:/app/migrations:ro
      - ./alembic.ini:/app/alembic.ini:ro
    command: ["sh","-lc","alembic upgrade head || true"]

  seed:
    image: postgres:15-alpine
    container_name: mep-seed
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./seeds:/seeds:ro
    command: ["sh","-lc","psql postgresql://postgres:postgres@db:5432/market_edge -f /seeds/ohlcv_seed.sql || true"]

volumes:
  mep_db_data:
