services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: mep-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: market_edge
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d market_edge"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - mep_db_data:/var/lib/postgresql/data

  migrate:
    build: .
    container_name: mep-migrate
    depends_on:
      db: { condition: service_healthy }
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@db:5432/market_edge}
    command: >
      sh -lc "alembic upgrade head || echo 'alembic skipped'"
    restart: "no"

  seed:
    image: postgres:16
    container_name: mep-seed
    depends_on:
      db: { condition: service_healthy }
    environment:
      PGPASSWORD: postgres
    volumes:
      - ./seeds:/seeds:ro
    command: >
      bash -lc "test -f /seeds/ohlcv_seed.sql &&
                psql -h db -U postgres -d market_edge -f /seeds/ohlcv_seed.sql || echo 'no seeds'"

  app:
    build: .
    container_name: mep-app
    environment:
      HOST: 0.0.0.0
      PORT: "8010"
      API_KEYS: "${API_KEYS:-secret123}"
      DATABASE_URL: "${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@db:5432/market_edge}"
      RATE_LIMIT_RPS: "${RATE_LIMIT_RPS:-1000}"
      RATE_LIMIT_BURST: "${RATE_LIMIT_BURST:-2000}"
      CORS_ALLOW_ORIGINS: "${CORS_ALLOW_ORIGINS:-*}"
      PROCESS_MAX_FDS: "${PROCESS_MAX_FDS:-1048576}"
    ports: ["8010:8010"]
    depends_on:
      db:      { condition: service_healthy }
      migrate: { condition: service_completed_successfully }
      seed:    { condition: service_completed_successfully }
    command: uvicorn main1:app --host 0.0.0.0 --port 8010 --timeout-keep-alive 90
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8010/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  mep_db_data:
